### ISSUE TITLE
Problem installing nodejs for debian

### ISSUE THREAD

**Issue by jorjahung** [dmichel1/ansible-statsd#2]
TASK: [statsd | Install nodejs for debian] ************************************
fatal: [default] => failed to parse: SUDO-SUCCESS-gpwqjhyokhdxvdlyldkezqwjlxylunkv
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1416400583.4-270684893479993/apt", line 1907, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1416400583.4-270684893479993/apt", line 477, in main
    cache.open(progress=None)
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 151, in open
    self._cache = apt_pkg.Cache(progress)
SystemError: E:The value '*backports' is invalid for APT::Default-Release as such a release is not available in the sources

FATAL: all hosts have already failed -- aborting

**Comment by ivannovak** [comment]
@jorjahung Were you able to resolve this issue?

**Comment by jorjahung** [comment]
Yes

Sincerely,
Jorja

**Comment by ivannovak** [comment]
@jorjahung Would you be able to share how you resolved the issue?

**Comment by dmichel1** [comment]
@ivannovak there's an open PR that I missed somehow that appears to fix the issue.

I'll look into this more later this week

**Comment by ivannovak** [comment]
Thanks @dmichel1 I've resolved this by ensuring the backport source was available in my sources.list. Cheers.
